#include <stdio.h>
#include "eq-profiles.h"

// designated array initializer containing all of the EQ band levels we need
// EQ band levels were generated by GPT
const EqProfile profiles[EQ_PRESET_COUNT] = {
    [EQ_PRESET_NEUTRAL] = {
        .id = EQ_PRESET_NEUTRAL,
        .name = "Neutral",
        .gains_db = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        .presetName = "neutral"
    },

    [EQ_PRESET_BASS_PLUS] = {
        .id = EQ_PRESET_BASS_PLUS,
        .name = "BassPlus",
        .gains_db = {1.5f, 2.0f, 1.0f, 0, 0, 0, 0, 0, 0.5f, 0},
        .presetName = "BassPlus"
    },

    [EQ_PRESET_CLEAN_BASS] = {
        .id = EQ_PRESET_CLEAN_BASS,
        .name = "CleanBass",
        .gains_db = {0.5f, 1.0f, 0.5f, -1.5f, -1.0f, 0, 0, -0.5f, 0, 0},
        .presetName = "CleanBass"
    },

    [EQ_PRESET_ANTI_HARSH] = {
        .id = EQ_PRESET_ANTI_HARSH,
        .name = "AntiHarsh",
        .gains_db = {0, 0, 0, 0, 0, 0, -0.5f, -1.5f, -1.0f, 0},
        .presetName = "AntiHarsh"
    },

    [EQ_PRESET_VOCAL_CLARITY] = {
        .id = EQ_PRESET_VOCAL_CLARITY,
        .name = "VocalClarity",
        .gains_db = {0, 0, 0, -0.5f, 0, 0.5f, 1.0f, 0.5f, 0, 0},
        .presetName = "VocalClarity"
    },

    [EQ_PRESET_WARMTH] = {
        .id = EQ_PRESET_WARMTH,
        .name = "Warmth",
        .gains_db = {0, 0.5f, 1.0f, 1.0f, 0.5f, 0, -0.5f, -0.5f, 0, 0},
        .presetName = "Warmth"
    }
};

const EqProfile *eq_profile_get(EqPresetID id) {
    if (id < 0 || id >= EQ_PRESET_COUNT) {
        return &profiles[EQ_PRESET_NEUTRAL]; // by default, preset is neutral
    }

    return &profiles[id];
}

void printProfile(const EqProfile *profile) {
    printf("profile: %s\n", profile->name);
    printf("preset to apply: %s\n", profile->presetName);

    printf("EQ bands: ");

    for (int i = 0; i < EQ_BAND_COUNT; i++) {
        printf("%f", profile->gains_db[i]);
    }

    printf("\n");
}
